repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        fail_fast: true
      - id: end-of-file-fixer
        fail_fast: true
      - id: check-yaml
        fail_fast: true
      - id: check-added-large-files
        fail_fast: true
      - id: check-merge-conflict
        fail_fast: true

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        fail_fast: true

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E203,W503,F541,E231"]
        fail_fast: true

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true

      - id: tests
        name: run test suite
        entry: python -m pytest tests/ -v -s --tb=short
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        fail_fast: true

      - id: coverage
        name: coverage
        entry: bash -c 'coverage run -m pytest && coverage report --fail-under=80 --show-missing --skip-covered'
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-commit, pre-push]
